---
- name: Include variables based on the operating system
  include_vars: '{{ ansible_os_family }}.yml'

# @action Ensures cloudflared is installed
# Installs cloudflared on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: 'install-{{ ansible_os_family }}.yml'
